create table "public"."rooms" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "red" bigint,
    "blue" bigint,
    "timer" smallint,
    "name" text,
    "ready" boolean default false,
    "cycle" smallint default '0'::smallint,
    "status" text,
    "heroes_pool" jsonb default '{}'::jsonb,
    "discussion_round" boolean default true
);


create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "isTurn" boolean default false,
    "ready" boolean default false,
    "color" text,
    "room" bigint,
    "heroes_pool" jsonb default '{}'::jsonb,
    "heroes_selected" jsonb default '{}'::jsonb,
    "number_of_pick" smallint default '2'::smallint,
    "name" text
);
