create table "public"."rooms" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "red" bigint,
    "blue" bigint,
    "timer" text,
    "name" text,
    "ready" boolean default false,
    "cycle" smallint not null default '-1'::smallint,
    "status" text,
    "heroes_pool" jsonb default '{}'::jsonb
);


create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "isturn" boolean default false,
    "ready" boolean default false,
    "color" text,
    "room" bigint,
    "heroes_selected" jsonb,
    "name" text,
    "selected_hero" text,
    "clicked_hero" text,
    "heroes_ban" jsonb
);


CREATE UNIQUE INDEX rooms_pkey ON public.rooms USING btree (id);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

alter table "public"."rooms" add constraint "rooms_pkey" PRIMARY KEY using index "rooms_pkey";

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."rooms" add constraint "rooms_blue_fkey" FOREIGN KEY (blue) REFERENCES teams(id) ON DELETE CASCADE not valid;

alter table "public"."rooms" validate constraint "rooms_blue_fkey";

alter table "public"."rooms" add constraint "rooms_red_fkey" FOREIGN KEY (red) REFERENCES teams(id) ON DELETE CASCADE not valid;

alter table "public"."rooms" validate constraint "rooms_red_fkey";

alter table "public"."teams" add constraint "teams_room_fkey" FOREIGN KEY (room) REFERENCES rooms(id) ON DELETE CASCADE not valid;

alter table "public"."teams" validate constraint "teams_room_fkey";


